export const SET_SINGER = 'SET_SINGER';

export const SET_PLAYING_STATE = 'SET_PLAYING_STATE';

export const SET_FULL_SCREEN = 'SET_FULL_SCREEN';

export const SET_PLAY_LIST = 'SET_PLAY_LIST';

export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST';

export const SET_PLAY_MODE = 'SET_PLAY_MODE';

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX';

export const SET_DISC = 'SET_DISC';

export const SET_TOP_LIST = 'SET_TOP_LIST';

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY';

export const SET_PLAY_HISTORY = 'SET_PLAY_HISTORY';

export const SET_FAVORITE_LIST = 'SET_FAVORITE_LIST';

export const SET_FAVORITE_LIST_LIST = 'SET_FAVORITE_LIST_LIST';

export const SET_USER_CENTER_VISIBLE = 'SET_USER_CENTER_VISIBLE';

export const SET_PLAY_LIST_VISIBLE = 'SET_PLAY_LIST_VISIBLE';

export const SET_MINI_PLAYER_VISIBLE = 'SET_MINI_PLAYER_VISIBLE';

export const SET_POPUP_VISIBLE = 'SET_POPUP_VISIBLE';

export const SET_POPUP_CONTENT = 'SET_POP_CONTENT';

export const UPDATE_DIRECTION = 'UPDATE_DIRECTION';

export const SET_SRC_TYPES = 'SET_SRC_TYPES';

export const SET_HAS_LOGIN = 'SET_HAS_LOGIN';

export const SET_USER_INFO = 'SET_USER_INFO';
